// Package domain defines the core business entities of the media management
// application. These structs are pure data carriers with no dependencies on
// infrastructure (database, HTTP, file system). All other layers import domain,
// but domain imports nothing from the application.
//
// This is the innermost ring of the Clean Architecture: it represents the
// "what" of the business, not the "how".
package domain

import (
	"time"

	"github.com/google/uuid"
)

// MediaType represents the kind of media file (image or video).
// It is derived from content sniffing, not from user input or file extension,
// to prevent spoofing (e.g., uploading an .exe renamed to .jpg).
type MediaType string

const (
	MediaTypeImage MediaType = "image"
	MediaTypeVideo MediaType = "video"
)

// Media represents a media item (photo or video) in the system.
//
// Key invariants:
//   - ID is always a valid UUID, generated by the database.
//   - Name is a human-readable label chosen by the uploader.
//   - Type is derived from content sniffing (http.DetectContentType), never
//     from the client-provided Content-Type header or file extension.
//   - FilePath is the storage-relative path (e.g., "4/f/3/uuid.jpg" for local,
//     or an S3 key). It is never an absolute filesystem path.
//   - OriginalName is the filename provided by the client, stored for display
//     purposes only. It is NEVER used for storage (path traversal prevention).
//   - Tags may be empty (media without tags is allowed).
type Media struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Type         MediaType `json:"type"`
	FilePath     string    `json:"-"`              // internal, not exposed directly
	OriginalName string    `json:"originalName"`
	FileSize     int64     `json:"fileSize"`
	Tags         []Tag     `json:"tags"`
	CreatedAt    time.Time `json:"createdAt"`
}
